### ISSUE TITLE
Gzip doesn't work

### ISSUE THREAD

**Issue by speedwheel** [iris-contrib/examples#20] opened 2017-08-04 17:54 UTC
I am trying to enable gzip for all the website, but getting the following error in the browser's
 console for my static files: `"Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH".`

If I disable Gzip everything works fine.

![bbbb](https://user-images.githubusercontent.com/5404341/28980828-f76f7a78-7957-11e7-83ff-87636a882359.PNG)

This is the code I've used inside Iris:

```go
app = iris.New()
app.Use(func(ctx context.Context) {
    ctx.Gzip(true)
})
```

I am using the latest version of Iris, Ubuntu 16.04 and Chrome.

 Any thoughts?

**Comment by hiveminded** [comment] 2017-08-11 10:35
@speedwheel can't reproduce that...gzip works here

**Comment by kataras** [comment] 2017-08-12 05:55
Gzip was working but `StaticWeb` had the issue because of its internal `serveFile` and `serveContent`, they should be fixed now, **follow this thread instead**: https://github.com/kataras/iris/issues/717

**Closed** 2017-08-12 05:55 UTC
